# Generated by Django 3.0.1 on 2020-07-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('bgroup', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('med', models.CharField(max_length=50)),
                ('bill', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=50)),
                ('date1', models.CharField(max_length=50)),
                ('date2', models.CharField(default='2020-07-09', max_length=50)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
